### ISSUE TITLE
Icons not visible in Spanish Translation

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-site#51]
In the Spanish translations, some icons/images are missing:
![imagen](https://user-images.githubusercontent.com/1789408/188950457-604d411c-0d66-4e68-914a-5d1d88dfc6a5.png)

..which exists in the English version:
![imagen](https://user-images.githubusercontent.com/1789408/188950940-e6b53258-1f8e-4bf5-a113-a8858d6d50a5.png)

**Comment by rvergara** [comment]
resuelto via pull request por RamiroV13
